
package com.customerservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CustomerServiceService", targetNamespace = "http://com/", wsdlLocation = "http://localhost:8080/EmployeeService/cust?wsdl")
public class CustomerServiceService
    extends Service
{

    private final static URL CUSTOMERSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.customerservice.CustomerServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.customerservice.CustomerServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/EmployeeService/cust?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/EmployeeService/cust?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CUSTOMERSERVICESERVICE_WSDL_LOCATION = url;
    }

    public CustomerServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerServiceService() {
        super(CUSTOMERSERVICESERVICE_WSDL_LOCATION, new QName("http://com/", "CustomerServiceService"));
    }

    /**
     * 
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "customerServicePort")
    public CustomerService getCustomerServicePort() {
        return super.getPort(new QName("http://com/", "customerServicePort"), CustomerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "customerServicePort")
    public CustomerService getCustomerServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/", "customerServicePort"), CustomerService.class, features);
    }

}
